version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: books
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

#  app:
#    build: .
#    container_name: book-api
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/books
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD:

volumes:
  mysql_data:
